// #132: TOML config merge — the Codex `config.toml` twin of the JSON
// deep-merge discipline. The user-scope file (~/.codex/config.toml) is the
// runtime's REAL config: trust settings, model choice, unrelated machine
// entries. Merging must preserve every foreign key; --force wins ONLY the
// collided keys; uninstall removes only the pack's contribution.
import { describe, it, expect } from "vitest";
import { parse as parseToml } from "smol-toml";
import {
  mergeTomlConfig,
  forceMergeTomlConfig,
  removeTomlFragment,
  tomlFragmentIntact,
  TOML_MERGE_PATHS,
} from "../src/install/merge.js";

const USER_CONFIG = `# my hand-written codex config
model = "gpt-5.3-codex"
approval_policy = "on-request"

[projects."/home/me/dev/secret"]
trust_level = "trusted"

[mcp_servers.local-db]
command = "db-mcp"
args = ["--port", "5432"]
`;

const PACK_FRAGMENT = `# Generated by AgentPack for me.pack@1.0.0
[agentpack]
pack_id = "me.pack"
pack_version = "1.0.0"

[mcp_servers.github]
command = "github-mcp"
`;

describe("mergeTomlConfig", () => {
  it("deep-merges the pack fragment into an existing config — every foreign key survives", () => {
    const res = mergeTomlConfig(USER_CONFIG, PACK_FRAGMENT);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    const merged = parseToml(res.merged) as Record<string, unknown>;
    // Foreign keys: trust settings, model, unrelated MCP server.
    expect(merged["model"]).toBe("gpt-5.3-codex");
    expect(merged["approval_policy"]).toBe("on-request");
    expect(
      (merged["projects"] as Record<string, Record<string, unknown>>)[
        "/home/me/dev/secret"
      ]["trust_level"],
    ).toBe("trusted");
    const servers = merged["mcp_servers"] as Record<string, Record<string, unknown>>;
    expect(servers["local-db"]["command"]).toBe("db-mcp");
    // Pack entries landed alongside.
    expect(servers["github"]["command"]).toBe("github-mcp");
    expect((merged["agentpack"] as Record<string, unknown>)["pack_id"]).toBe("me.pack");
  });

  it("reports a collision when an existing key differs (never silently overwrites)", () => {
    const existing = `model = "gpt-5.3-codex"\n\n[mcp_servers.github]\ncommand = "my-own-github"\n`;
    const res = mergeTomlConfig(existing, PACK_FRAGMENT);
    expect(res.ok).toBe(false);
    if (res.ok) return;
    expect("collisions" in res && res.collisions).toContain("mcp_servers.github");
  });

  it("re-install replaces the prior fragment instead of colliding with it", () => {
    const first = mergeTomlConfig(USER_CONFIG, PACK_FRAGMENT);
    expect(first.ok).toBe(true);
    if (!first.ok) return;
    const v2 = PACK_FRAGMENT.replace('pack_version = "1.0.0"', 'pack_version = "2.0.0"');
    const res = mergeTomlConfig(first.merged, v2, PACK_FRAGMENT);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    const merged = parseToml(res.merged) as Record<string, unknown>;
    expect((merged["agentpack"] as Record<string, unknown>)["pack_version"]).toBe("2.0.0");
    expect(merged["model"]).toBe("gpt-5.3-codex");
  });

  it("returns invalidToml for unparseable existing content", () => {
    const res = mergeTomlConfig("not = [valid", PACK_FRAGMENT);
    expect(res.ok).toBe(false);
    if (res.ok) return;
    expect("invalidToml" in res && res.invalidToml).toBe(true);
  });

  it("TOML datetimes in the existing config survive the round trip as datetimes", () => {
    const existing = `last_login = 2026-07-01T10:00:00Z\n`;
    const res = mergeTomlConfig(existing, PACK_FRAGMENT);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    const merged = parseToml(res.merged) as Record<string, unknown>;
    expect(merged["last_login"]).toBeInstanceOf(Date);
  });
});

describe("forceMergeTomlConfig", () => {
  it("the pack wins ONLY the collided key; every other user entry survives", () => {
    const existing = `model = "gpt-5.3-codex"

[projects."/home/me/dev/secret"]
trust_level = "trusted"

[mcp_servers.github]
command = "my-own-github"
`;
    const forced = forceMergeTomlConfig(existing, PACK_FRAGMENT);
    expect(forced).not.toBeNull();
    const merged = parseToml(forced!) as Record<string, unknown>;
    // Collided key: pack wins.
    const servers = merged["mcp_servers"] as Record<string, Record<string, unknown>>;
    expect(servers["github"]["command"]).toBe("github-mcp");
    // Foreign keys survive — a --force apply must never replace the file whole.
    expect(merged["model"]).toBe("gpt-5.3-codex");
    expect(
      (merged["projects"] as Record<string, Record<string, unknown>>)[
        "/home/me/dev/secret"
      ]["trust_level"],
    ).toBe("trusted");
  });

  it("returns null when the existing content is not parseable TOML", () => {
    expect(forceMergeTomlConfig("not = [valid", PACK_FRAGMENT)).toBeNull();
  });
});

describe("removeTomlFragment + tomlFragmentIntact", () => {
  it("uninstall removes only the pack's entries; user entries remain", () => {
    const merged = mergeTomlConfig(USER_CONFIG, PACK_FRAGMENT);
    expect(merged.ok).toBe(true);
    if (!merged.ok) return;
    expect(tomlFragmentIntact(merged.merged, PACK_FRAGMENT)).toBe(true);
    const remainder = removeTomlFragment(merged.merged, PACK_FRAGMENT);
    expect(remainder).not.toBeNull();
    const rest = parseToml(remainder!) as Record<string, unknown>;
    expect(rest["model"]).toBe("gpt-5.3-codex");
    const servers = rest["mcp_servers"] as Record<string, Record<string, unknown>>;
    expect(servers["local-db"]).toBeDefined();
    expect(servers["github"]).toBeUndefined();
    expect(rest["agentpack"]).toBeUndefined();
  });

  it("returns the empty string when nothing remains (pack-created file)", () => {
    const onlyOurs = mergeTomlConfig("", PACK_FRAGMENT);
    expect(onlyOurs.ok).toBe(true);
    if (!onlyOurs.ok) return;
    expect(removeTomlFragment(onlyOurs.merged, PACK_FRAGMENT)).toBe("");
  });

  it("fragmentIntact is false after the user tampers with the pack's entry", () => {
    const merged = mergeTomlConfig(USER_CONFIG, PACK_FRAGMENT);
    expect(merged.ok).toBe(true);
    if (!merged.ok) return;
    const tampered = merged.merged.replace('command = "github-mcp"', 'command = "evil"');
    expect(tomlFragmentIntact(tampered, PACK_FRAGMENT)).toBe(false);
  });
});

describe("hardening", () => {
  it("refuses configs carrying prototype-pollution keys", () => {
    const evil = `[__proto__]\npolluted = true\n`;
    const res = mergeTomlConfig(evil, PACK_FRAGMENT);
    expect(res.ok).toBe(false);
    if (res.ok) return;
    expect("invalidToml" in res && res.invalidToml).toBe(true);
  });

  it("TOML_MERGE_PATHS covers the project and user-scope forms of the codex config", () => {
    expect(TOML_MERGE_PATHS.has(".codex/config.toml")).toBe(true);
    expect(TOML_MERGE_PATHS.has("config.toml")).toBe(true);
  });
});
