-- AgentPack Registry — initial schema migration.
--
-- Source: `Plans/PROTOCOL.md` § 4. Generated by hand to match the Drizzle
-- schema in `packages/db/src/schema/`. Re-emit by running
-- `pnpm --filter @agentpack/db db:generate` against a live DATABASE_URL once
-- one is available; the SQL should diff to empty.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "github_id" text NOT NULL UNIQUE,
  "username" text NOT NULL,
  "email" text,
  "name" text,
  "avatar_url" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- publishers + publisher_members
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "publishers" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "slug" text NOT NULL UNIQUE,
  "display_name" text NOT NULL,
  "verified" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "publisher_members" (
  "publisher_id" uuid NOT NULL REFERENCES "publishers"("id") ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "role" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("publisher_id", "user_id")
);

-- ---------------------------------------------------------------------------
-- packs + tsvector + GIN index
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "packs" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "publisher_id" uuid NOT NULL REFERENCES "publishers"("id") ON DELETE CASCADE,
  "slug" text NOT NULL,
  "name" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "tags" text[] NOT NULL DEFAULT '{}'::text[],
  "latest_version_id" uuid,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "search" tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce("name", '')), 'A') ||
    setweight(to_tsvector('english', coalesce("description", '')), 'B') ||
    setweight(to_tsvector('english', array_to_string(coalesce("tags", '{}'::text[]), ' ')), 'C')
  ) STORED
);
CREATE UNIQUE INDEX IF NOT EXISTS "packs_publisher_slug_uq" ON "packs" ("publisher_id", "slug");
CREATE INDEX IF NOT EXISTS "packs_search_idx" ON "packs" USING gin ("search");

-- ---------------------------------------------------------------------------
-- pack_versions
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE "pack_version_status" AS ENUM ('published','deprecated','yanked','quarantined','blocked');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "pack_versions" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "pack_id" uuid NOT NULL REFERENCES "packs"("id") ON DELETE CASCADE,
  "version" text NOT NULL,
  "status" "pack_version_status" NOT NULL DEFAULT 'published',
  "manifest_sha256" text NOT NULL,
  "manifest_r2_key" text NOT NULL,
  "readme_r2_key" text,
  "published_at" timestamptz NOT NULL DEFAULT now(),
  "published_by" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "pack_versions_pack_version_uq" ON "pack_versions" ("pack_id", "version");

-- Forward FK from packs.latest_version_id -> pack_versions(id). Deferred so a
-- pack can be inserted before its first version exists.
ALTER TABLE "packs"
  ADD CONSTRAINT "packs_latest_version_fk" FOREIGN KEY ("latest_version_id")
  REFERENCES "pack_versions"("id")
  DEFERRABLE INITIALLY DEFERRED;

-- ---------------------------------------------------------------------------
-- atoms
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "atoms" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "pack_version_id" uuid NOT NULL REFERENCES "pack_versions"("id") ON DELETE CASCADE,
  "atom_id" text NOT NULL,
  "type" text NOT NULL,
  "risk_level" text NOT NULL,
  "metadata" jsonb NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "atoms_pack_atom_uq" ON "atoms" ("pack_version_id", "atom_id");

-- ---------------------------------------------------------------------------
-- pack_files
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "pack_files" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "pack_version_id" uuid NOT NULL REFERENCES "pack_versions"("id") ON DELETE CASCADE,
  "atom_id" text,
  "path" text NOT NULL,
  "sha256" text NOT NULL,
  "bytes" integer NOT NULL,
  "r2_key" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "pack_files_pack_version_path_idx" ON "pack_files" ("pack_version_id", "path");

-- ---------------------------------------------------------------------------
-- compatibilities
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "compatibilities" (
  "pack_version_id" uuid NOT NULL REFERENCES "pack_versions"("id") ON DELETE CASCADE,
  "target" text NOT NULL,
  "status" text NOT NULL,
  PRIMARY KEY ("pack_version_id", "target")
);

-- ---------------------------------------------------------------------------
-- api_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "api_tokens" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "publisher_id" uuid REFERENCES "publishers"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "token_prefix" text NOT NULL,
  "token_sha256" text NOT NULL,
  "scopes" jsonb NOT NULL,
  "last_used_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "revoked_at" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "api_tokens_token_sha256_uq" ON "api_tokens" ("token_sha256");

-- ---------------------------------------------------------------------------
-- publishes (two-phase publish state)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "publishes" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "publisher_slug" text NOT NULL,
  "pack_slug" text NOT NULL,
  "version" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "expires_at" timestamptz NOT NULL,
  "created_by" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "pack_id" uuid REFERENCES "packs"("id") ON DELETE SET NULL,
  "presigned_files" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- reviews (POST returns 501 in v0.3; schema only)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "reviews" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "pack_version_id" uuid NOT NULL REFERENCES "pack_versions"("id") ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "rating" smallint NOT NULL,
  "body" text NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- audit_events (Phase 6-reserved hash-chained log)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "audit_events" (
  "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  "org_id" uuid,
  "actor_user_id" uuid REFERENCES "users"("id") ON DELETE RESTRICT,
  "action" text NOT NULL,
  "target_type" text NOT NULL,
  "target_id" text NOT NULL,
  "previous_entry_id" uuid REFERENCES "audit_events"("id") ON DELETE RESTRICT,
  "entry_checksum" text NOT NULL,
  "payload" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- NextAuth (Auth.js) adapter tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "accounts" (
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "type" text NOT NULL,
  "provider" text NOT NULL,
  "provider_account_id" text NOT NULL,
  "refresh_token" text,
  "access_token" text,
  "expires_at" integer,
  "token_type" text,
  "scope" text,
  "id_token" text,
  "session_state" text,
  PRIMARY KEY ("provider", "provider_account_id")
);

CREATE TABLE IF NOT EXISTS "sessions" (
  "session_token" text PRIMARY KEY,
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "expires" timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "verification_tokens" (
  "identifier" text NOT NULL,
  "token" text NOT NULL,
  "expires" timestamptz NOT NULL,
  PRIMARY KEY ("identifier", "token")
);
