import type { AdapterExportOptions, AdapterOutputFile, Atom } from "../schema/types.js";
import {
  atomsByType,
  defineAdapter,
  readAtomFile,
  stableJsonStringify,
} from "./types.js";

function toolStub(atom: Atom): string {
  const invocation = (atom as { invocation?: { slash?: string; cli?: string } })
    .invocation;
  const name = invocation?.cli ?? atom.id.split(":")[1] ?? atom.name;
  return `// Generated by workgraph-cli for AgentPack atom \`${atom.id}\`.
// This is a *stub* MCP tool definition for the ChatGPT Apps SDK. Adjust to
// match the current SDK surface — output here is intentionally conservative.

import type { Tool } from "@modelcontextprotocol/sdk/types.js";

export const tool: Tool = {
  name: ${JSON.stringify(name)},
  description: ${JSON.stringify(atom.description)},
  inputSchema: {
    type: "object",
    properties: {
      input: { type: "string", description: "User input for the command." },
    },
  },
};

export async function handler(args: { input?: string }): Promise<string> {
  // TODO: Wire to your actual implementation. This stub returns the input
  // echoed back so the round-trip is observable in development.
  return \`(\${${JSON.stringify(atom.id)}}) \${args.input ?? ""}\`;
}
`;
}

export const chatgptAdapter = defineAdapter({
  target: "chatgpt",
  async build(options: AdapterExportOptions) {
    const { manifest, packRoot, resolvedAtoms } = options;
    const files: AdapterOutputFile[] = [];
    const warnings: string[] = [];
    const unsupported: string[] = [];
    const byType = atomsByType(resolvedAtoms);

    warnings.push(
      "ChatGPT Apps SDK target is export-only. The generated app skeleton must be reviewed and registered manually.",
    );

    // ---------- project-instructions.md ----------
    const lines: string[] = [
      `# ${manifest.metadata.name}\n`,
      `> ${manifest.metadata.description}\n`,
      `Publisher: ${manifest.metadata.publisher} · Version: ${manifest.metadata.version} · Profile: ${options.profile}\n`,
    ];
    for (const atom of byType.get("instruction") ?? []) {
      const body = (await readAtomFile(packRoot, atom)) ?? atom.description;
      lines.push(`## ${atom.name}\n\n${body.trim()}\n`);
    }
    const ruleAtoms = byType.get("rule") ?? [];
    if (ruleAtoms.length > 0) {
      lines.push("## Rules\n");
      for (const atom of ruleAtoms) {
        lines.push(`- ${atom.name}: ${atom.description}`);
      }
    }
    files.push({
      path: "project-instructions.md",
      content: lines.join("\n") + "\n",
      action: "create",
    });

    // ---------- app-manifest.json ----------
    const commandAtoms = byType.get("command") ?? [];
    const mcpAtoms = byType.get("mcp_server") ?? [];
    const appManifest = {
      name: manifest.metadata.name,
      pack_id: manifest.metadata.id,
      version: manifest.metadata.version,
      description: manifest.metadata.description,
      experimental: true,
      tools: commandAtoms.map((atom) => ({
        atom: atom.id,
        name: atom.name,
        description: atom.description,
      })),
      mcp_servers: mcpAtoms.map((atom) => ({
        atom: atom.id,
        name: atom.name,
        description: atom.description,
        risk_level: atom.risk_level,
      })),
    };
    files.push({
      path: "app-manifest.json",
      content: stableJsonStringify(appManifest),
      action: "create",
    });

    // ---------- mcp-server/ skeleton ----------
    if (commandAtoms.length > 0) {
      files.push({
        path: "mcp-server/package.json",
        content:
          stableJsonStringify({
            name: `${manifest.metadata.slug}-mcp-server`,
            private: true,
            type: "module",
            version: manifest.metadata.version,
            dependencies: {
              "@modelcontextprotocol/sdk": "^1.0.0",
            },
            scripts: {
              start: "node src/index.ts",
            },
          }),
        action: "create",
      });
      files.push({
        path: "mcp-server/src/index.ts",
        content:
          `// Conservative MCP server skeleton for ${manifest.metadata.id}.\n` +
          `// Edit and wire to a real transport (stdio/http) before registering with ChatGPT.\n` +
          commandAtoms
            .map((atom) => {
              const slug = (atom.id.split(":")[1] ?? atom.name).replace(
                /[^a-zA-Z0-9_]/g,
                "_",
              );
              return `import { tool as ${slug}Tool, handler as ${slug}Handler } from "./tools/${atom.id.split(":")[1] ?? slug}.js";`;
            })
            .join("\n") +
          "\n\nexport const tools = [\n" +
          commandAtoms
            .map((a) => `  ${(a.id.split(":")[1] ?? a.name).replace(/[^a-zA-Z0-9_]/g, "_")}Tool`)
            .join(",\n") +
          "\n];\n",
        action: "create",
      });
      for (const atom of commandAtoms) {
        const slug = atom.id.split(":")[1] ?? atom.name;
        files.push({
          path: `mcp-server/src/tools/${slug}.ts`,
          content: toolStub(atom),
          action: "create",
        });
      }
    }

    // Hooks, subagents → unsupported
    for (const atom of byType.get("hook") ?? []) {
      warnings.push(`Hook atom \`${atom.id}\` — not supported by ChatGPT target.`);
      unsupported.push(atom.id);
    }
    for (const atom of byType.get("subagent") ?? []) {
      warnings.push(
        `Subagent atom \`${atom.id}\` — surfaced as instruction note only.`,
      );
    }

    return { files, warnings, unsupportedAtoms: unsupported };
  },
});
