import { parse as parseYaml } from "yaml";
import type { AdapterExportOptions, AdapterOutputFile, Atom } from "../schema/types.js";
import {
  atomsByType,
  defineAdapter,
  readAtomDirectory,
  readAtomFile,
  stableJsonStringify,
  wrapInstructionBlock,
} from "./types.js";

function tomlEscape(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")
    .replace(
      /[\u0000-\u001f\u007f]/g,
      (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`,
    );
}

function renderTomlValue(value: unknown): string {
  if (typeof value === "string") return `"${tomlEscape(value)}"`;
  if (typeof value === "number") {
    if (!Number.isFinite(value)) return `"${String(value)}"`;
    return String(value);
  }
  if (typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    return `[${value.map(renderTomlValue).join(", ")}]`;
  }
  // Nested objects are JSON-stringified into a TOML basic string to keep the
  // grammar simple and deterministic; consumers that want structured TOML
  // can parse the JSON. Better: don't pass nested objects through.
  return `"${tomlEscape(JSON.stringify(value))}"`;
}

function renderTomlTable(name: string, table: Record<string, unknown>): string {
  const keys = Object.keys(table).sort();
  const lines: string[] = [`[${name}]`];
  for (const k of keys) {
    const v = table[k];
    if (v === undefined) continue;
    lines.push(`${k} = ${renderTomlValue(v)}`);
  }
  return lines.join("\n") + "\n";
}

function slugFor(atom: Atom): string {
  const raw = atom.id.split(":")[1] ?? atom.name;
  return raw.replace(/[^a-zA-Z0-9._-]/g, "_");
}

export const codexAdapter = defineAdapter({
  target: "codex",
  async build(options: AdapterExportOptions) {
    const { manifest, packRoot, resolvedAtoms } = options;
    const files: AdapterOutputFile[] = [];
    const warnings: string[] = [];
    const unsupported: string[] = [];
    const byType = atomsByType(resolvedAtoms);

    // ---------- AGENTS.md ----------
    const sections: string[] = [`# ${manifest.metadata.name}\n`];
    sections.push(
      `> ${manifest.metadata.description}\n\n` +
        `Publisher: \`${manifest.metadata.publisher}\` · Version: \`${manifest.metadata.version}\` · Profile: \`${options.profile}\`\n`,
    );

    for (const atom of byType.get("instruction") ?? []) {
      const body = (await readAtomFile(packRoot, atom)) ?? atom.description;
      sections.push(`## ${atom.name}\n\n_(${atom.id})_\n\n${body.trim()}\n`);
    }
    const ruleAtoms = byType.get("rule") ?? [];
    if (ruleAtoms.length > 0) {
      sections.push(`## Rules\n`);
      for (const atom of ruleAtoms) {
        sections.push(`### ${atom.name}\n\n_(${atom.id})_\n\n${atom.description}\n`);
      }
    }
    const workflowAtoms = byType.get("workflow") ?? [];
    if (workflowAtoms.length > 0) {
      sections.push(`## Workflows\n`);
      for (const atom of workflowAtoms) {
        sections.push(`### ${atom.name}\n\n${atom.description}\n`);
      }
    }
    files.push({
      path: "AGENTS.md",
      content: wrapInstructionBlock(manifest.metadata.id, sections.join("\n")),
      action: "create",
    });

    // ---------- .codex/config.toml ----------
    const meta = {
      pack_id: manifest.metadata.id,
      pack_version: manifest.metadata.version,
      profile: options.profile,
      generated_by: "workgraph-cli",
    };
    const tomlBlocks: string[] = [
      `# Generated by workgraph for AgentPack ${manifest.metadata.id}@${manifest.metadata.version}`,
      `# Profile: ${options.profile}`,
      "",
      renderTomlTable("agentpack", meta),
    ];

    const mcpAtoms = byType.get("mcp_server") ?? [];
    for (const atom of mcpAtoms) {
      const slug = slugFor(atom);
      const a = atom as {
        transport?: string;
        command?: string;
        args?: string[];
        env?: Record<string, unknown>;
      };
      const envKeys = Object.keys(a.env ?? {});
      tomlBlocks.push(
        renderTomlTable(`mcp_servers.${slug}`, {
          transport: a.transport ?? "stdio",
          command: a.command ?? "",
          args: a.args ?? [],
          env_vars: envKeys,
          risk_level: atom.risk_level,
          description: atom.description,
        }),
      );
      warnings.push(
        `MCP server \`${atom.id}\` configured. Required env: ${envKeys.join(", ") || "(none)"}.`,
      );
    }

    files.push({
      path: ".codex/config.toml",
      content: tomlBlocks.join("\n"),
      action: "create",
    });

    // ---------- .codex/hooks.json ----------
    const allowedShellCommands = manifest.permissions?.shell?.commands ?? [];
    const hookAtoms = byType.get("hook") ?? [];
    if (hookAtoms.length > 0) {
      const hooks: Record<string, unknown[]> = {};
      for (const atom of hookAtoms) {
        const parsed = await parseAtomYaml(packRoot, atom);
        const events = ((
          parsed?.["events"] as { codex?: string[]; generic?: string[] } | undefined
        )?.codex ??
          (parsed?.["events"] as { generic?: string[] } | undefined)?.generic ?? [
            "after_edit",
          ]) as string[];
        const handler =
          (parsed?.["handler"] as { command?: string } | undefined) ??
          (atom as { handler?: { command?: string } }).handler;
        const command = handler?.command ?? "";
        if (
          !command ||
          !allowedShellCommands.includes(command) ||
          /\bsh\s+-c\b|\bbash\s+-c\b|\bnode\s+-e\b|\beval\b/i.test(command)
        ) {
          warnings.push(
            `Hook \`${atom.id}\` command \`${command || "(empty)"}\` is not in \`permissions.shell.commands\` or contains a shell escape. Refusing to emit it.`,
          );
          unsupported.push(atom.id);
          continue;
        }
        for (const evt of events) {
          const list = hooks[evt] ?? [];
          list.push({
            command,
            description: atom.description,
            risk_level: atom.risk_level,
            source_atom: atom.id,
          });
          hooks[evt] = list;
        }
      }
      if (Object.keys(hooks).length > 0) {
        files.push({
          path: ".codex/hooks.json",
          content: stableJsonStringify({ hooks }),
          action: "create",
        });
        warnings.push(
          "Hook atom(s) installed — `.codex/hooks.json` declares shell commands after edits.",
        );
      }
    }

    // ---------- .codex/skills ----------
    for (const atom of byType.get("skill") ?? []) {
      const slug = slugFor(atom);
      const entries = await readAtomDirectory(packRoot, atom);
      if (entries.length === 0) {
        warnings.push(
          `Skill \`${atom.id}\` directory not found at \`${atom.path}\`; emitting minimal SKILL.md.`,
        );
        files.push({
          path: `.codex/skills/${slug}/SKILL.md`,
          content: `---\nname: ${slug}\ndescription: ${atom.description}\n---\n\n# ${atom.name}\n\n${atom.description}\n`,
          action: "create",
        });
      } else {
        for (const entry of entries) {
          files.push({
            path: `.codex/skills/${slug}/${entry.relPath}`,
            content: entry.content,
            action: "create",
          });
        }
      }
    }

    // ---------- .codex/skills (commands) ----------
    for (const atom of byType.get("command") ?? []) {
      const slug = slugFor(atom);
      const parsed = await parseAtomYaml(packRoot, atom);
      let body: string | null = null;
      const promptPath = parsed?.["prompt"];
      if (typeof promptPath === "string" && promptPath.length > 0) {
        body = await readSafeRelative(packRoot, promptPath);
      }
      files.push({
        path: `.codex/skills/${slug}/SKILL.md`,
        content: `---\nname: ${slug}\ndescription: ${atom.description}\n---\n\n# ${atom.name}\n\n${body ?? atom.description}\n`,
        action: "create",
      });
    }

    // ---------- .codex/agents (subagents) ----------
    for (const atom of byType.get("subagent") ?? []) {
      const slug = slugFor(atom);
      const tomlTable = {
        id: slug,
        name: atom.name,
        description: atom.description,
        risk_level: atom.risk_level,
        source_atom: atom.id,
      };
      files.push({
        path: `.codex/agents/${slug}.toml`,
        content:
          `# Conservative Codex subagent definition — verify against your Codex version.\n` +
          renderTomlTable("agent", tomlTable),
        action: "create",
      });
    }

    const supportedTypes = new Set([
      "instruction",
      "rule",
      "workflow",
      "skill",
      "command",
      "subagent",
      "hook",
      "mcp_server",
    ]);
    for (const r of resolvedAtoms) {
      if (!supportedTypes.has(r.atom.type)) {
        unsupported.push(r.atom.id);
        warnings.push(
          `Atom \`${r.atom.id}\` of type \`${r.atom.type}\` is not mapped by the Codex adapter.`,
        );
      }
    }

    return { files, warnings, unsupportedAtoms: unsupported };
  },
});

async function parseAtomYaml(
  packRoot: string,
  atom: Atom,
): Promise<Record<string, unknown> | null> {
  const raw = await readAtomFile(packRoot, atom);
  if (!raw) return null;
  try {
    const parsed = parseYaml(raw) as unknown;
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
    return null;
  } catch {
    return null;
  }
}

async function readSafeRelative(packRoot: string, relPath: string): Promise<string | null> {
  const path = await import("node:path");
  const fs = await import("node:fs/promises");
  if (
    path.isAbsolute(relPath) ||
    relPath.startsWith("~") ||
    relPath.split(/[\\/]+/).includes("..")
  ) {
    return null;
  }
  const target = path.resolve(packRoot, relPath);
  const rel = path.relative(packRoot, target);
  if (rel.startsWith("..") || path.isAbsolute(rel)) return null;
  try {
    return await fs.readFile(target, "utf8");
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "ENOENT") return null;
    throw err;
  }
}
