import type {
  AdapterExportOptions,
  AdapterOutputFile,
  Atom,
} from "../schema/types.js";
import {
  atomsByType,
  defineAdapter,
  readAtomDirectory,
  readAtomFile,
  stableJsonStringify,
  wrapInstructionBlock,
} from "./types.js";

function tomlEscape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function renderTomlValue(value: unknown): string {
  if (typeof value === "string") return `"${tomlEscape(value)}"`;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    return `[${value.map(renderTomlValue).join(", ")}]`;
  }
  return `"${tomlEscape(JSON.stringify(value))}"`;
}

function renderTomlTable(name: string, table: Record<string, unknown>): string {
  const keys = Object.keys(table).sort();
  const lines: string[] = [`[${name}]`];
  for (const k of keys) {
    const v = table[k];
    if (v === undefined) continue;
    lines.push(`${k} = ${renderTomlValue(v)}`);
  }
  return lines.join("\n") + "\n";
}

export const codexAdapter = defineAdapter({
  target: "codex",
  async build(options: AdapterExportOptions) {
    const { manifest, packRoot, resolvedAtoms } = options;
    const files: AdapterOutputFile[] = [];
    const warnings: string[] = [];
    const unsupported: string[] = [];
    const byType = atomsByType(resolvedAtoms);

    // ---------- AGENTS.md ----------
    const sections: string[] = [`# ${manifest.metadata.name}\n`];
    sections.push(
      `> ${manifest.metadata.description}\n\n` +
        `Publisher: \`${manifest.metadata.publisher}\` · Version: \`${manifest.metadata.version}\` · Profile: \`${options.profile}\`\n`,
    );

    for (const atom of byType.get("instruction") ?? []) {
      const body = (await readAtomFile(packRoot, atom)) ?? atom.description;
      sections.push(`## ${atom.name}\n\n_(${atom.id})_\n\n${body.trim()}\n`);
    }
    const ruleAtoms = byType.get("rule") ?? [];
    if (ruleAtoms.length > 0) {
      sections.push(`## Rules\n`);
      for (const atom of ruleAtoms) {
        sections.push(
          `### ${atom.name}\n\n_(${atom.id})_\n\n${atom.description}\n`,
        );
      }
    }
    const workflowAtoms = byType.get("workflow") ?? [];
    if (workflowAtoms.length > 0) {
      sections.push(`## Workflows\n`);
      for (const atom of workflowAtoms) {
        sections.push(`### ${atom.name}\n\n${atom.description}\n`);
      }
    }
    files.push({
      path: "AGENTS.md",
      content: wrapInstructionBlock(manifest.metadata.id, sections.join("\n")),
      action: "create",
    });

    // ---------- .codex/config.toml ----------
    const meta = {
      pack_id: manifest.metadata.id,
      pack_version: manifest.metadata.version,
      profile: options.profile,
      generated_by: "workgraph-cli",
    };
    const tomlBlocks: string[] = [
      `# Generated by workgraph for AgentPack ${manifest.metadata.id}@${manifest.metadata.version}`,
      `# Profile: ${options.profile}`,
      "",
      renderTomlTable("agentpack", meta),
    ];

    // mcp_servers as TOML tables
    const mcpAtoms = byType.get("mcp_server") ?? [];
    for (const atom of mcpAtoms) {
      const slug = atom.id.split(":")[1] ?? atom.name;
      const a = atom as {
        transport?: string;
        command?: string;
        args?: string[];
        env?: Record<string, unknown>;
      };
      const envKeys = Object.keys(a.env ?? {});
      tomlBlocks.push(
        renderTomlTable(`mcp_servers.${slug}`, {
          transport: a.transport ?? "stdio",
          command: a.command ?? "",
          args: a.args ?? [],
          env_required: envKeys,
          risk_level: atom.risk_level,
          description: atom.description,
        }),
      );
      warnings.push(
        `MCP server \`${atom.id}\` configured. Required env: ${envKeys.join(", ") || "(none)"}.`,
      );
    }

    files.push({
      path: ".codex/config.toml",
      content: tomlBlocks.join("\n"),
      action: "create",
    });

    // ---------- .codex/hooks.json ----------
    const hookAtoms = byType.get("hook") ?? [];
    if (hookAtoms.length > 0) {
      const hooks: Record<string, unknown[]> = {};
      for (const atom of hookAtoms) {
        const events =
          (atom as { lifecycle?: { events?: { codex?: string[]; generic?: string[] } } })
            .lifecycle?.events?.codex ??
          (atom as { lifecycle?: { events?: { generic?: string[] } } }).lifecycle
            ?.events?.generic ??
          ["after_edit"];
        for (const evt of events) {
          const list = hooks[evt] ?? [];
          list.push({
            command: (atom as { handler?: { command?: string } }).handler?.command ??
              "echo noop",
            description: atom.description,
            risk_level: atom.risk_level,
            source_atom: atom.id,
          });
          hooks[evt] = list;
        }
      }
      files.push({
        path: ".codex/hooks.json",
        content: stableJsonStringify({ hooks }),
        action: "create",
      });
      warnings.push(
        "Hook atom(s) installed — `.codex/hooks.json` declares shell commands after edits.",
      );
    }

    // ---------- .codex/skills ----------
    for (const atom of byType.get("skill") ?? []) {
      const slug = atom.id.split(":")[1] ?? atom.name;
      const entries = await readAtomDirectory(packRoot, atom);
      if (entries.length === 0) {
        files.push({
          path: `.codex/skills/${slug}/SKILL.md`,
          content: `---\nname: ${slug}\ndescription: ${atom.description}\n---\n\n# ${atom.name}\n\n${atom.description}\n`,
          action: "create",
        });
      } else {
        for (const entry of entries) {
          files.push({
            path: `.codex/skills/${slug}/${entry.relPath}`,
            content: entry.content,
            action: "create",
          });
        }
      }
    }

    // ---------- .codex/skills (commands) ----------
    for (const atom of byType.get("command") ?? []) {
      const slug = atom.id.split(":")[1] ?? atom.name;
      const raw = await readAtomFile(packRoot, atom);
      let body: string | null = null;
      if (raw) {
        const promptPath = /^prompt:\s*(.+)$/m.exec(raw)?.[1]?.trim();
        if (promptPath) {
          const { readFile } = await import("node:fs/promises");
          const pathMod = await import("node:path");
          try {
            body = await readFile(
              pathMod.resolve(packRoot, promptPath),
              "utf8",
            );
          } catch {
            body = null;
          }
        }
      }
      files.push({
        path: `.codex/skills/${slug}/SKILL.md`,
        content: `---\nname: ${slug}\ndescription: ${atom.description}\n---\n\n# ${atom.name}\n\n${body ?? atom.description}\n`,
        action: "create",
      });
    }

    // ---------- .codex/agents (subagents) ----------
    for (const atom of byType.get("subagent") ?? []) {
      const slug = atom.id.split(":")[1] ?? atom.name;
      const tomlTable = {
        id: slug,
        name: atom.name,
        description: atom.description,
        risk_level: atom.risk_level,
        source_atom: atom.id,
      };
      files.push({
        path: `.codex/agents/${slug}.toml`,
        content:
          `# Conservative Codex subagent definition — verify against your Codex version.\n` +
          renderTomlTable("agent", tomlTable),
        action: "create",
      });
    }

    // Unsupported
    const supportedTypes = new Set([
      "instruction",
      "rule",
      "workflow",
      "skill",
      "command",
      "subagent",
      "hook",
      "mcp_server",
    ]);
    for (const r of resolvedAtoms) {
      if (!supportedTypes.has(r.atom.type)) {
        unsupported.push(r.atom.id);
        warnings.push(
          `Atom \`${r.atom.id}\` of type \`${r.atom.type}\` is not mapped by the Codex adapter.`,
        );
      }
    }

    return { files, warnings, unsupportedAtoms: unsupported };
  },
});
